[MOOV-2174]: Added failure card payment attempts
nofrixion/moneymoov-dotnet pull request #201
Opened 2023-10-03 09:32 UTC by agranillonf

Added failed card payment attempts to the PaymentRequest PaymentAttempts collection.

2023-10-03 10:35 UTC, sauravmaiti22 commented
This will work nicely for checkout but after looking at the code seems like we are not recording a card setup failure event for cybersource. There will be abandoned cardsetupauthentication events in that case I believe. Need to test it. 

Also, we are recording error responses for card_authorise event. So those failures need to be accounted for as well. See usages of RecordCardSubmitPaymentErrorResponse. Sale event can also be logged with error responses.

2023-10-03 10:38 UTC, sauravmaiti22 requested changes
This will work nicely for checkout but after looking at the code seems like we are not recording a card setup failure event for cybersource. There will be abandoned cardsetupauthentication events in that case I believe. Need to test it.

Also, we are recording error responses for card_authorise event. So those failures need to be accounted for as well. See usages of RecordCardSubmitPaymentErrorResponse. Sale event can also be logged with error responses.

2023-10-04 08:31 UTC, arifmatin approved these changes

2023-10-05 09:12 UTC, sauravmaiti22 approved these changes

2023-10-05 18:30 UTC, merged