Support for receiving data in case of non-success response
nofrixion/moneymoov-dotnet pull request #417
Opened 2024-09-18 17:26 UTC by sauravmaiti22

Tribe has a different response model which doesn't quite fit in the RestApiResponse we have. We receive the data even in case of non-success response, and the data has the error message. So added a flag to try and deserialise the data even on error response.

2024-09-19 07:56 UTC, donalnofrixion requested changes

2024-09-19 07:56 UTC, donalnofrixion commented on src/NoFrixion.MoneyMoov/RestClient/RestApiClient.cs
> +        catch (System.Text.Json.JsonException)
Why have both catches here? Surely it's one or the other?

2024-09-20 15:27 UTC, arifmatin approved these changes

2024-09-20 15:46 UTC, agranillonf approved these changes

2024-09-20 20:35 UTC, Publicker approved these changes

2024-09-21 11:31 UTC, merged