MOOV-3764: Direct Debit payment request updates
nofrixion/moneymoov-dotnet pull request #431
Opened 2024-10-11 22:18 UTC by agranillonf

- Added DirectDebitAccountID field to payment request model, interface and features. This will be used very similarly to the PispAccountID, but for Direct Debit logic.
- Updated the Direct Debit payment request status logic, so that when a user submits a payment with a mandate, the payment request gets marked as `Authorized`, and when the corresponding transaction is received, it'll transition to `FullyPaid`, `PartiallyPaid` or `OverPaid` accordingly.

2024-10-13 17:51 UTC, sipsorcery commented
We will cause ourselves problems if we support `DirectDebitAccountID` an customers start using it.

One DD's are supported on agency banking the destination account for each creditor ID gets set by BC.

I think for now we'd be better off using the existing `IsDefault` flag on one of the merchan'ts accounts.

2024-10-13 17:51 UTC, sipsorcery requested changes
Don't use DirectDebitAccountID.

2024-10-14 19:21 UTC, sipsorcery approved these changes

2024-10-15 08:24 UTC, donalnofrixion approved these changes

2024-10-15 13:58 UTC, merged