Moved PaymentRequestEnum to SDK
nofrixion/moneymoov-dotnet pull request #9
Opened 2022-08-02 17:38 UTC by sauravmaiti22

Moved PaymentRequestEnum to SDK

2022-08-02 17:51 UTC, donalnofrixion commented
I'd remove the commented out values. We don't want them visible in the sdk.

2022-08-02 23:25 UTC, sipsorcery requested changes

2022-08-02 23:25 UTC, sipsorcery commented on src/NoFrixion.MoneyMoov/Enums/PaymentResultEnum.cs
> +//  Proprietary NoFrixion.
License is MIT.

2022-08-03 10:17 UTC, donalnofrixion approved these changes

2022-08-04 07:37 UTC, merged